image: barichello/godot-ci:4.4.1

stages:
  - export
  - serve

variables:
  EXPORT_NAME: Space_Scout
  ARTIFACTS_DIR: "/srv/artifacts"
  NGINX_PORT: 8080
  DOCKER_HOST: "unix:///var/run/docker.sock"
  DOCKER_TLS_CERTDIR: ""
  WEB_CONTAINER_NAME: "spacescout-web"
  WEB_HOST_PORT: 8443  # HTTPS port on the host

before_script:
  - mkdir -v -p build/linux
  - mkdir -v -p build/windows
  - mkdir -v -p build/mac
  - mkdir -v -p build/web
  - mkdir -v -p build/android

linux:
  stage: export
  script:
    - godot --headless --verbose --export-release "Linux" ./build/linux/$EXPORT_NAME.x86_64
  artifacts:
    name: $EXPORT_NAME-$CI_JOB_NAME
    paths:
      - build/linux

windows:
  stage: export
  script:
    - godot --headless --verbose --export-release "Windows Desktop" ./build/windows/$EXPORT_NAME.exe
  artifacts:
    name: $EXPORT_NAME-$CI_JOB_NAME
    paths:
      - build/windows

mac:
  stage: export
  script:
    - godot --headless --verbose --export-release "macOS" ./build/mac/$EXPORT_NAME.zip
  artifacts:
    name: $EXPORT_NAME-$CI_JOB_NAME
    paths:
      - build/mac

android:
  stage: export
  script:
    - godot --headless --verbose --export-release "Android" ./build/android/$EXPORT_NAME.apk
  artifacts:
    name: $EXPORT_NAME-$CI_JOB_NAME
    paths:
      - build/android

web:
  stage: export
  script:
    - godot --headless --verbose --export-release "Web" ./build/web/index.html
  artifacts:
    name: $EXPORT_NAME-$CI_JOB_NAME
    paths:
      - build/web

serve:
  stage: serve
  image: docker:24.0.5-git
  services:
    - docker:24.0.5-dind
  dependencies:
    - web
  before_script:
    - docker info
  script:
    # Create SSL certificates directory on the Docker host
    - mkdir -p /mnt/docker/compose/volumes/spacescout/ssl
    
    # Generate self-signed SSL certificate if not exists
    - |
      if [ ! -f /mnt/docker/compose/volumes/spacescout/ssl/cert.pem ]; then
        apk add --no-cache openssl
        openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
          -keyout /mnt/docker/compose/volumes/spacescout/ssl/privkey.pem \
          -out /mnt/docker/compose/volumes/spacescout/ssl/cert.pem \
          -subj "/CN=spacescout.home"
      fi
    
    # Create nginx config
    - |
      cat > nginx.conf << EOF
      server {
          listen 443 ssl;
          server_name spacescout.home;
          
          ssl_certificate /etc/nginx/ssl/cert.pem;
          ssl_certificate_key /etc/nginx/ssl/privkey.pem;
          
          location / {
              root /usr/share/nginx/html;
              index index.html;
              try_files \$uri \$uri/ /index.html;
          }
          
          location /downloads/ {
              alias /usr/share/nginx/downloads/;
              autoindex on;
          }
      }
      EOF
    
    # Stop and remove existing container if it exists
    - docker rm -f $WEB_CONTAINER_NAME || true
    
    # Create directory structure for downloads
    - mkdir -p /mnt/docker/compose/volumes/spacescout/downloads
    
    # Copy all build artifacts to downloads directory
    - cp -R build/* /mnt/docker/compose/volumes/spacescout/downloads/
    
    # Start nginx container with HTTPS
    - |
      docker run -d \
        --name $WEB_CONTAINER_NAME \
        --restart always \
        -p $WEB_HOST_PORT:443 \
        -v /mnt/docker/compose/volumes/spacescout/ssl:/etc/nginx/ssl:ro \
        -v /mnt/docker/compose/volumes/spacescout/downloads:/usr/share/nginx/downloads:ro \
        -v $(pwd)/build/web:/usr/share/nginx/html:ro \
        -v $(pwd)/nginx.conf:/etc/nginx/conf.d/default.conf:ro \
        nginx:alpine
    
    # Verify container is running
    - docker ps | grep $WEB_CONTAINER_NAME
    
    # Output access information
    - echo "Game web build is now available at https://spacescout.home:$WEB_HOST_PORT"
    - echo "Download all builds at https://spacescout.home:$WEB_HOST_PORT/downloads/"
  only:
    - master

